[package]
name = "dlm"
version = "0.4.3"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Minimal download manager"
repository = "https://github.com/agourlay/dlm"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["cli", "http", "download", "download-manager"]
edition = "2021"

[dependencies]
futures-util = "0.3.31"
reqwest = { version = "0.12.9", default-features = false, features = ["http2", "gzip", "rustls-tls"] }
tokio-stream = { version = "0.1.16", features = ["io-util"] }
tokio = { version = "1.41.1", features = ["rt-multi-thread", "fs", "macros", "signal"] }
tokio-util = "0.7.12"
tokio-retry = "0.3.0"
async-channel = "2.3.1"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["cargo"] }
indicatif = "0.17.8"
thiserror = "2.0.3"
rand = "0.8.5"
